# Generated by Django 5.2.11 on 2026-02-24 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspisaniya', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='students',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teachers',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='students', to='raspisaniya.subject'),
        ),
        migrations.CreateModel(
            name='LessonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=80)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='raspisaniya.lesson')),
                ('students', models.ManyToManyField(to='raspisaniya.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspisaniya.teacher')),
            ],
        ),
    ]
