# Generated by Django 5.2.11 on 2026-02-28 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspisaniya', '0003_group_student_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessongroup',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='lessongroup',
            name='start_time',
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='lessongroup',
            name='group_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lessongroup',
            name='students',
            field=models.ManyToManyField(blank=True, to='raspisaniya.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='debts',
            field=models.ManyToManyField(blank=True, related_name='debt_students', to='raspisaniya.subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='raspisaniya.subject'),
        ),
        migrations.CreateModel(
            name='LessonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lesson_number', models.PositiveIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='raspisaniya.lesson')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
