# Generated by Django 5.2.11 on 2026-03-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspisaniya', '0004_remove_lessongroup_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Rus'), ('qq', 'Qoraqalpoq'), ('en', 'Ingliz')], default='uz', max_length=10),
        ),
    ]
