# Generated by Django 5.2.11 on 2026-03-07 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspisaniya', '0005_student_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='lessongroup',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lessongroup',
            name='students',
        ),
        migrations.RemoveField(
            model_name='lessongroup',
            name='teacher',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_lessons', models.PositiveIntegerField()),
                ('lessons_per_week', models.PositiveIntegerField()),
                ('lesson_duration', models.PositiveIntegerField(default=80)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspisaniya.subject')),
            ],
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.PositiveIntegerField(default=1)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('weekdays', models.JSONField(default=list)),
                ('language', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Rus'), ('qq', 'Qoraqalpoq'), ('en', 'Ingliz')], default='uz', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='raspisaniya.course')),
                ('students', models.ManyToManyField(blank=True, to='raspisaniya.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspisaniya.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='GroupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lesson_number', models.PositiveIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='raspisaniya.coursegroup')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='LessonSchedule',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='LessonGroup',
        ),
    ]
