# Generated by Django 5.2.11 on 2026-03-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspisaniya', '0006_remove_lesson_subject_remove_lessongroup_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='weekdays',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
