# Generated by Django 5.2.11 on 2026-03-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspisaniya', '0008_student_student_id_student_user_teacher_teacher_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupschedule',
            name='lesson_number',
            field=models.IntegerField(default=1),
        ),
    ]
