# Generated by Django 5.2.11 on 2026-03-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspisaniya', '0010_room_coursegroup_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='include_saturday',
            field=models.BooleanField(default=False),
        ),
    ]
