# Generated by Django 5.2.11 on 2026-04-30 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspisaniya', '0012_alter_student_user_alter_teacher_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspisaniya.groupschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspisaniya.student')),
            ],
            options={
                'unique_together': {('student', 'schedule')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midterm', models.FloatField(blank=True, null=True)),
                ('current', models.FloatField(blank=True, null=True)),
                ('final', models.FloatField(blank=True, null=True)),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspisaniya.coursegroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspisaniya.student')),
            ],
            options={
                'unique_together': {('student', 'course_group')},
            },
        ),
    ]
