# Generated by Django 5.2.11 on 2026-05-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspisaniya', '0014_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupschedule',
            name='teacher_can_edit',
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='teacher_can_edit',
            field=models.BooleanField(default=False),
        ),
    ]
