# Generated by Django 5.2.11 on 2026-06-08 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspisaniya', '0015_remove_groupschedule_teacher_can_edit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_grades', to='raspisaniya.groupschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_grades', to='raspisaniya.student')),
            ],
            options={
                'ordering': ['schedule__date'],
                'unique_together': {('student', 'schedule')},
            },
        ),
    ]
