# Generated by Django 5.2.11 on 2026-06-16 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspisaniya', '0016_dailygrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='raspisaniya.teacher'),
        ),
    ]
