# Generated by Django 5.2.11 on 2026-07-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspisaniya', '0017_alter_coursegroup_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='display_col',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]