# Generated by Django 5.2.11 on 2026-04-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
    ]

from django.db import migrations
from django.contrib.auth.models import User

def create_default_admin(apps, schema_editor):
    # Agar 'admin' foydalanuvchisi mavjud bo'lmasa, uni yaratadi
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(
            username='admin',
            email='xolburiyev@gmail.com',
            password='Sohib030'
        )

def remove_default_admin(apps, schema_editor):
    # Migratsiyani qaytarib olishda adminni o'chiradi
    User.objects.filter(username='admin').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'), # Bu yerda 0001_initial bog'liqligi turishi kerak
    ]

    operations = [
        migrations.RunPython(create_default_admin, remove_default_admin),
    ]